### ISSUE TITLE
Exit on Start

### ISSUE THREAD

**Issue by Quest79** [elytra/BTFU#12]
[fml-server-latest.log](https://github.com/elytra/BTFU/files/1649824/fml-server-latest.log)

Startup bat:
java -XX:+UseG1GC -Xmx6g -Xms6g -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -Dfml.debugExit=true -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar forge-1.10.2-12.18.3.2511-universal.jar nogui pause

Whats up with the exit each time I try to start?

**Comment by unascribed** [comment]
```
[06:29:57] [Server thread/WARN] [FML/BTFU]: ****************************************
[06:29:57] [Server thread/WARN] [FML/BTFU]: * This mod backs up your entire minecraft directory, so the backups directory cannot be inside your minecraft directory.
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at btfubackup.BTFU$.init(BTFU.scala:27)
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at btfubackup.BTFU.init(BTFU.scala)
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:29:57] [Server thread/WARN] [FML/BTFU]: *  at java.lang.reflect.Method.invoke(Unknown Source)...
[06:29:57] [Server thread/WARN] [FML/BTFU]: ****************************************
```
